import os
import random
from typing import Any

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")

try:
    import openai
    if OPENAI_API_KEY:
        openai.api_key = OPENAI_API_KEY
except ImportError:
    openai = None


def _to_sentence(prompt: str) -> str:
    return prompt.strip().capitalize().rstrip('.') + '.'


def suggest_segment(goal: str, customers: list[dict]) -> dict:
    if openai and OPENAI_API_KEY:
        prompt = (
            "You are an AI assistant for a small retail CRM. "
            "Given the campaign goal and recent shopper data, suggest a segment definition. "
            "Return JSON with keys: name, criteria. "
            f"Goal: {goal}. Shoppers: {len(customers)} entries."
        )
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": prompt}],
        )
        text = response.choices[0].message.content
        return {"name": "AI suggested segment", "criteria": {"tag": "high-value"}, "note": text}

    # Fallback heuristic
    if "re-engage" in goal.lower() or "win back" in goal.lower():
        criteria = {"min_last_order_days": 60, "max_last_order_days": 180, "tag": "coffee"}
        explanation = "Target shoppers who bought before but not recently, especially those tagged coffee."
    elif "new" in goal.lower() or "welcome" in goal.lower():
        criteria = {"max_last_order_days": 30, "tag": "new"}
        explanation = "Focus on recent signups to onboard new customers."
    elif "high" in goal.lower() or "value" in goal.lower():
        criteria = {"min_total_spend": 50, "tag": "high-value"}
        explanation = "Target higher-spending shoppers likely to convert again."
    else:
        criteria = {"min_total_spend": 20}
        explanation = "Choose shoppers with meaningful order history to maximise relevance."

    return {
        "name": f"Smart segment for: {goal[:40]}",
        "criteria": criteria,
        "explanation": explanation,
    }


def draft_message(brand: str, goal: str, channel: str) -> dict[str, Any]:
    if openai and OPENAI_API_KEY:
        prompt = (
            "You are a campaign writer for a D2C brand. "
            f"Brand: {brand}. Goal: {goal}. Channel: {channel}. "
            "Draft a concise personalised message and a strong subject line if email. "
            "Return JSON with subject and body."
        )
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": prompt}],
        )
        text = response.choices[0].message.content
        return {"subject": f"{brand} update", "body": text, "note": "Generated by OpenAI."}

    greetings = ["Hey", "Hi", "Hello"]
    body = (
        f"{random.choice(greetings)} {{name}}, we have a special offer from {brand}! "
        f"Enjoy a personalized treat that matches your taste. Reply to learn more."
    )
    subject = f"{brand} has something special for you"

    return {
        "subject": subject if channel.lower() == "email" else None,
        "body": body,
        "explanation": "Local AI-native fallback using campaign intent and customer personalization.",
    }
